name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Telity/TuristGuide@v1
      - name: Last Files
        run: |
          pwd 
          ls -a
      - name: simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: 'Hej Nikolaj'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"